services:
  _defaults:
    autowire: true
    autoconfigure: true



  Vanguard\Tournaments\:
    resource: '../src/'
    exclude:
      - '../src/**/DataFixture/'
      - '../src/**/DependencyInjection/'
      - '../src/**/Entity/'
